### ISSUE TITLE
Class 'kartik\widgets\SideNav' not found

### ISSUE THREAD

**Issue by gugoan** [Patroklo/yii2-menu#1]
I have no set "options" and get de error _Class 'kartik\widgets\SideNav' not found_

You could put a complete example please?

**Comment by Patroklo** [comment]
No problem, I'll check it.

**Comment by Patroklo** [comment]
The Kartik namespace was wrong. It should work just fine now.

**Comment by gugoan** [comment]
Fixed!
Thanks :)
