### ISSUE TITLE
Doubts in the parameter $options

### ISSUE THREAD

**Issue by gugoan** [Patroklo/yii2-menu#2]
Must use the list in http://demos.krajee.com/widget-details/sidenav#sidenav-options?

I tried to use some but not worked (**headingOptions** for example) .
How Removing the header ?

**Comment by Patroklo** [comment]
Hi! Right now I'm implementing a new widget for the package that will let use the basic menu widget. 

About the heading in this case:

[options => ['heading' => false]]

Should to the trick to remove the header.

**Comment by gugoan** [comment]
hi! work fine..
thanks...
