### ISSUE TITLE
Active menu by default

### ISSUE THREAD

**Issue by gugoan** [Patroklo/yii2-menu#3]
How do I the parent categories come active (open) by default?
class = "active"

In the example below, and BOOKS CATEGORIES always appear open:

![print4](https://cloud.githubusercontent.com/assets/1585443/9027837/ab52e742-393a-11e5-8a1c-115e800cc1c1.png)

**Comment by Patroklo** [comment]
Hi, that's a Kartik Sidenav issue, right now I can't quite remember how to do it, check their documentation, probably they'll explain it
http://demos.krajee.com/widget-details/sidenav#sidenav-options

**Comment by gugoan** [comment]
ok, thanks Patroklo :)
